Repository publishpress/PublishPress-Checklists, pull requests merged in 2020-07, with the labels that each got.

#153 #52-Internal link requirement
  core/Requirement/Internal_links.php
  modules/checklists/assets/js/meta-box.js
  modules/checklists/checklists.php
Labels: enhancement

#154 #86-yoast-seo-check
  composer.json
  core/Legacy/LegacyPlugin.php
  modules/yoastSeo/assets/js/meta-box.js
  modules/yoastSeo/lib/Requirement/Readability_Analysis.php
  modules/yoastSeo/lib/Requirement/Seo_Analysis.php
  modules/yoastSeo/yoastSeo.php
Labels: Useful new requirements, enhancement

#160 Release 2.2.0
  .babelrc
  composer.lock
  includes.php
  languages/publishpress-checklists-fr_FR.mo
  languages/publishpress-checklists-fr_FR.po
  modules/checklists/assets/css/admin-pages.css
  modules/checklists/assets/css/post-editor-checklists.css
  modules/checklists/assets/js/gutenberg-warning.jsx
  modules/checklists/assets/js/gutenberg-warning.min.js
  modules/checklists/assets/js/meta-box.js
  package-lock.json
  package.json
  publishpress-checklists.php
  readme.txt
Labels: release
